import { Chat, Complete, Email, Process, Question } from "@/assets/icon";
import { useApiQuery } from "@/hooks/getCmsUpdate";
import { useApiMutation } from "@/hooks/useApiMutation";
import { Book, Phone, X } from "lucide-react"; // Added X icon for closing modal
import React, { useState } from "react";
import { FaPlus } from "react-icons/fa";
import { ScrollRestoration } from "react-router-dom";

const Support = () => {
  const [isPlusAccording, setIsPlusAccording] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  // Form State
  const [formData, setFormData] = useState({
    subject: "",
    description: "",
    priority: "medium",
    category: "",
  });

  const { data: faqData } = useApiQuery({
    queryKey: "faqs",
    url: "/faqs",
    secure: true,
  });
  const { data: supportCenter } = useApiQuery({
    queryKey: "support-center",
    url: "/support-center",
    secure: true,
  });
  const { data: supportTickets } = useApiQuery({
    queryKey: "support-tickets",
    url: "/support-tickets",
    secure: true,
  });

  const addNewTicket = useApiMutation({
    url: "/support-tickets/store",
    method: "post",
    secure: true,
    successMessage: "Ticket created successfully!",
    invalidateKeys: ["support-tickets"],
  });

  // Handle Input Change
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  // Handle Form Submission
  const handleAddTicket = (e) => {
    e.preventDefault();

    // specific payload structure requested
    const payload = {
      ...formData,
      ticket_status: "open", // Default status
      // Note: ticket_number is usually generated by backend. 
      // If you strictly need to send it from frontend, uncomment line below:
      // ticket_number: `Ticket-${Math.floor(Math.random() * 1000)}`, 
    };

    addNewTicket.mutate(payload, {
      onSuccess: () => {
        setIsModalOpen(false);
        setFormData({ // Reset form
          subject: "",
          description: "",
          priority: "medium",
          category: "",
        });
      },
    });
  };

  const handleBorderClick = (index) =>
    setIsPlusAccording((prevIndex) => (prevIndex === index ? null : index));

  return (
    <div className="relative">
      <ScrollRestoration />
      <h2 className="text-xl sm:text-2xl md:text-3xl font-bold my-2 text-[#000000]">
        Support Center
      </h2>
      <p className="text-sm text-[#4B5563]">
        Get help and support for your investment journey
      </p>

      {/* Support Center Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-8 mt-8">
        {supportCenter?.data?.map((item, index) => (
          <div
            key={index}
            className="bg-[#ffffff] p-5 rounded-2xl flex flex-col justify-center items-center shadow-md"
          >
            <img
              src={item?.image}
              alt={item?.title}
              className="w-12 h-12 mb-2"
            />
            <h2 className="text-[17px] font-bold my-1 text-[#000000]">
              {item?.title}
            </h2>
            <div
              className="text-sm text-[#4B5563] my-1"
              dangerouslySetInnerHTML={{ __html: item?.description }}
            />
            {item?.phone && (
              <p className="text-sm text-[#4B5563] my-1">{item.phone}</p>
            )}
            {item?.email && (
              <p className="text-sm text-[#4B5563] my-1">{item.email}</p>
            )}
            <a
              href={item?.email ? `mailto:${item.email}` : `tel:${item.phone}`}
              className="px-3 py-2 text-[15px] bg-custom-primary border duration-300 text-white hover:bg-black rounded-lg mt-2 cursor-pointer w-full text-center block"
            >
              {item?.button_text}
            </a>
          </div>
        ))}
      </div>

      <div className="flex flex-col md:flex-row w-full gap-10 mt-6">
        {/* Left Side: Ticket List */}
        <div className="w-full md:w-1/2">
          <div className="flex items-center justify-between my-4">
            <h2 className="md:text-[22px] font-bold">My Support Tickets</h2>
            <button
              onClick={() => setIsModalOpen(true)}
              className="px-3 py-2 text-[15px] bg-custom-primary border duration-300 text-white hover:bg-black rounded-lg mt-2 cursor-pointer"
            >
              New Ticket
            </button>
          </div>
          <div className="space-y-4">
            {supportTickets?.data?.map((item, index) => (
              <div
                key={index}
                className="bg-[#ffffff] p-5 rounded-2xl  shadow-md"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <h2 className="sm:text-lg font-bold">{item?.subject}</h2>
                    <div className="flex flex-col sm:flex-row items-center gap-2">
                      <button className="bg-[#DBEAFE] text-[#1E40AF] text-sm font-medium px-3 py-1 rounded-2xl flex items-center gap-2">
                        <Question /> {item?.ticket_status}
                      </button>
                      <button className="bg-[#FEF9C3] text-[#854D0E] text-sm font-medium px-3 py-1 rounded-2xl">
                        {item?.priority}
                      </button>
                    </div>
                  </div>
                </div>
                <p className="text-sm text-[#4B5563] my-1">
                  {item?.ticket_number}
                </p>
                <div className="flex items-center justify-between text-[15px] my-1 text-[#4B5563]">
                  <p>Created: {item?.created_at}</p>
                  <p>Updated: {item?.updated_at}</p>
                </div>
                {/* <button className="px-3 py-2 text-[15px] bg-[#FFF] border hover:text-white hover:bg-black rounded-lg mt-2 cursor-pointer">
                  View Details
                </button> */}
              </div>
            ))}
          </div>
        </div>

        {/* Right Side: FAQ */}
        <div className="w-full md:w-1/2">
          <div className="flex items-center justify-between my-4">
            <h2 className="text-lg md:text-[22px] font-bold">
              Frequently Asked Questions
            </h2>
            {/* <button className="px-3 py-2 text-[15px] bg-custom-primary duration-300 text-white border  hover:bg-black rounded-lg mt-2 cursor-pointer flex items-center gap-2">
              <Book size={18} /> View All
            </button> */}
          </div>
          <div className="">
            {faqData?.data?.map((according, index) => (
              <article
                key={index}
                className="border-b dark:border-b-slate-800 p-3"
              >
                <div
                  className="flex gap-2 cursor-pointer items-center justify-between w-full"
                  onClick={() => handleBorderClick(index)}
                >
                  <h2 className="text-black font-[500] text-[1rem]">
                    {according?.question}
                  </h2>
                  <p>
                    <FaPlus
                      className={`text-[1rem] lg:text-[1.2rem] text-slate-600 text-text transition-all duration-300 ${
                        isPlusAccording === index &&
                        "rotate-[45deg] !text-custom-secondary"
                      }`}
                    />
                  </p>
                </div>
                <div
                  className={`grid transition-all duration-300 overflow-hidden ease-in-out ${
                    isPlusAccording === index
                      ? "grid-rows-[1fr] opacity-100 mt-4"
                      : "grid-rows-[0fr] opacity-0"
                  }`}
                >
                  <p
                    className="text-[#424242] dark:text-[#abc2d3] text-[0.9rem] overflow-hidden"
                    dangerouslySetInnerHTML={{ __html: according?.answer }}
                  ></p>
                </div>
              </article>
            ))}
          </div>
        </div>
      </div>

      {/* --- CREATE TICKET MODAL --- */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
          <div className="bg-white rounded-2xl w-full max-w-lg p-6 shadow-2xl relative animate-in fade-in zoom-in duration-200">
            {/* Close Button */}
            <button
              onClick={() => setIsModalOpen(false)}
              className="absolute top-4 right-4 text-gray-500 hover:text-red-500 transition-colors"
            >
              <X size={24} />
            </button>

            <h2 className="text-xl font-bold mb-4 text-black">Create New Ticket</h2>
            
            <form onSubmit={handleAddTicket} className="space-y-4">
              {/* Subject */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Subject</label>
                <input
                  type="text"
                  name="subject"
                  required
                  value={formData.subject}
                  onChange={handleInputChange}
                  className="w-full border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-custom-primary"
                  placeholder="e.g., Question about dividend payments"
                />
              </div>

              {/* Category */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Category (Optional)</label>
                <input
                  type="text"
                  name="category"
                  value={formData.category}
                  onChange={handleInputChange}
                  className="w-full border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-custom-primary"
                  placeholder="e.g., Payment"
                />
              </div>

              {/* Priority */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Priority</label>
                <select
                  name="priority"
                  value={formData.priority}
                  onChange={handleInputChange}
                  className="w-full border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-custom-primary bg-white"
                >
                  <option value="low">Low</option>
                  <option value="medium">Medium</option>
                  <option value="high">High</option>
                </select>
              </div>

              {/* Description */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                <textarea
                  name="description"
                  required
                  rows="4"
                  value={formData.description}
                  onChange={handleInputChange}
                  className="w-full border border-gray-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-custom-primary"
                  placeholder="Describe your issue here..."
                />
              </div>

              {/* Submit Button */}
              <button
                type="submit"
                disabled={addNewTicket.isPending}
                className="w-full bg-custom-primary text-white font-semibold py-2.5 rounded-lg hover:bg-black transition-colors duration-300"
              >
                {addNewTicket.isPending ? "Creating..." : "Submit Ticket"}
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default Support;